<a href="https://colab.research.google.com/github/yogitas1/Proposed-Data-Driven-Insights-Using-SQL-Project-/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Notes per csv

#game
  #notes about code
  #FGM (goals made), FGA (goals attempted), fg_pct (fgm/fga)
  #fg3m series = 3 pointers
  #ftm = free thrown
  #oerb=# of team offensive rebounds
  #dreb=# of team defensive rebounds
  #reb=# of team rebounds
  #ast=# of team assists
  #stl=# of team steals
  #blk=# of team blocks
  #tov=# of team turnovers
  #pf=# of team personal fouls
#game_summary
  #many blanks in game sequence?
  #what is game_status?
  #what live pc time?
  #remove broadcast column?
  #what is wh? all column has 1
  #should game code be changed? wasn't listed anywhere else
#team_details
  #if string not avalible, should it be left as Null?
#team_history
  #can there be the same nickname for 2 teams?
#team_info_common
  #completely blank
#draft_history
  #some blanks in organization, what does that mean

#focus on home/away team statistics
#def team succes
  #nba way diff then team success, dont focus on that aspects, btu focus on what columns would be meaningful to you

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#!pip install sqlalchemy==1.3.23
import seaborn as sns
#import sqlite3 as sql

In [ ]:
!pip install ipython-sql

Requirement already satisfied: ipython-sql in /usr/local/lib/python3.10/dist-packages (0.5.0)
Requirement already satisfied: prettytable in /usr/local/lib/python3.10/dist-packages (from ipython-sql) (3.10.2)
Requirement already satisfied: ipython in /usr/local/lib/python3.10/dist-packages (from ipython-sql) (7.34.0)
Collecting sqlalchemy>=2.0 (from ipython-sql)
  Downloading SQLAlchemy-2.0.31-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.10/dist-packages (from ipython-sql) (0.5.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.10/dist-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy>=2.0->ipython-sql) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy>=2.0->ipython-sql) (3.0.3)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (71.0.4)
Collecting jedi>=0.16 (from ipython->ipython-sql)
  Downloading jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (3.0.47)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (2.16.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prettytable->ipython-sql) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Downloading SQLAlchemy-2.0.31-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 21.8 MB/s eta 0:00:00
Downloading jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 30.6 MB/s eta 0:00:00
Installing collected packages: sqlalchemy, jedi
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.3.23
    Uninstalling SQLAlchemy-1.3.23:
      Successfully uninstalled SQLAlchemy-1.3.23
Successfully installed jedi-0.19.1 sqlalchemy-2.0.31

In [ ]:
%load_ext sql

In [ ]:
#load game data
game = pd.read_csv('/content/game.csv')
game

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,...,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away,season_type
0,21946,1610610035,HUS,Toronto Huskies,24600001,1946-11-01 00:00:00,HUS vs. NYK,L,0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,68.0,2,0,Regular Season
1,21946,1610610034,BOM,St. Louis Bombers,24600003,1946-11-02 00:00:00,BOM vs. PIT,W,0,20.0,...,NaN,NaN,NaN,NaN,NaN,25.0,51.0,-5,0,Regular Season
2,21946,1610610032,PRO,Providence Steamrollers,24600002,1946-11-02 00:00:00,PRO vs. BOS,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,-6,0,Regular Season
3,21946,1610610025,CHS,Chicago Stags,24600004,1946-11-02 00:00:00,CHS vs. NYK,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,22.0,47.0,-16,0,Regular Season
4,21946,1610610028,DEF,Detroit Falcons,24600005,1946-11-02 00:00:00,DEF vs. WAS,L,0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,50.0,17,0,Regular Season
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65693,42022,1610612748,MIA,Miami Heat,42200403,2023-06-07 00:00:00,MIA vs. DEN,L,240,34.0,...,58.0,28.0,3.0,5.0,14.0,18.0,109.0,15,1,Playoffs
65694,42022,1610612748,MIA,Miami Heat,42200404,2023-06-09 00:00:00,MIA vs. DEN,L,240,35.0,...,34.0,26.0,11.0,7.0,8.0,18.0,108.0,13,1,Playoffs
65695,42022,1610612743,DEN,Denver Nuggets,42200405,2023-06-12 00:00:00,DEN vs. MIA,W,240,38.0,...,44.0,18.0,9.0,7.0,8.0,21.0,89.0,-5,1,Playoffs
65696,32022,1610616834,LBN,Team LeBron,32200001,2023-02-19 00:00:00,LBN vs. GNS,L,221,79.0,...,46.0,43.0,8.0,1.0,12.0,2.0,184.0,9,1,All-Star
65697,32022,1610616834,LBN,Team LeBron,32200001,2023-02-19 00:00:00,LBN vs. GNS,L,221,79.0,...,46.0,43.0,8.0,1.0,12.0,2.0,184.0,9,1,All Star

In [ ]:
#changing date format, removing time
game['game_date']=game['game_date'].str.slice(0,10)
game

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,...,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away,season_type
0,21946,1610610035,HUS,Toronto Huskies,24600001,1946-11-01,HUS vs. NYK,L,0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,68.0,2,0,Regular Season
1,21946,1610610034,BOM,St. Louis Bombers,24600003,1946-11-02,BOM vs. PIT,W,0,20.0,...,NaN,NaN,NaN,NaN,NaN,25.0,51.0,-5,0,Regular Season
2,21946,1610610032,PRO,Providence Steamrollers,24600002,1946-11-02,PRO vs. BOS,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,-6,0,Regular Season
3,21946,1610610025,CHS,Chicago Stags,24600004,1946-11-02,CHS vs. NYK,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,22.0,47.0,-16,0,Regular Season
4,21946,1610610028,DEF,Detroit Falcons,24600005,1946-11-02,DEF vs. WAS,L,0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,50.0,17,0,Regular Season
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65693,42022,1610612748,MIA,Miami Heat,42200403,2023-06-07,MIA vs. DEN,L,240,34.0,...,58.0,28.0,3.0,5.0,14.0,18.0,109.0,15,1,Playoffs
65694,42022,1610612748,MIA,Miami Heat,42200404,2023-06-09,MIA vs. DEN,L,240,35.0,...,34.0,26.0,11.0,7.0,8.0,18.0,108.0,13,1,Playoffs
65695,42022,1610612743,DEN,Denver Nuggets,42200405,2023-06-12,DEN vs. MIA,W,240,38.0,...,44.0,18.0,9.0,7.0,8.0,21.0,89.0,-5,1,Playoffs
65696,32022,1610616834,LBN,Team LeBron,32200001,2023-02-19,LBN vs. GNS,L,221,79.0,...,46.0,43.0,8.0,1.0,12.0,2.0,184.0,9,1,All-Star
65697,32022,1610616834,LBN,Team LeBron,32200001,2023-02-19,LBN vs. GNS,L,221,79.0,...,46.0,43.0,8.0,1.0,12.0,2.0,184.0,9,1,All Star

In [ ]:
#filling nulls with 0
game['fga_home']=game['fga_home'].fillna(0)
game['fga_away']=game['fga_away'].fillna(0)
game['fgm_home']=game['fgm_home'].fillna(0)
game['fgm_away']=game['fgm_away'].fillna(0)
game['fg3a_home']=game['fg3a_home'].fillna(0)
game['fg3a_away']=game['fg3a_away'].fillna(0)
game['fg3m_home']=game['fg3m_home'].fillna(0)
game['fg3m_away']=game['fg3m_away'].fillna(0)
game['ftm_home']=game['ftm_home'].fillna(0)
game['ftm_away']=game['ftm_away'].fillna(0)
game['fta_home']=game['fta_home'].fillna(0)
game['fta_away']=game['fta_away'].fillna(0)
game['fg_pct_home']=game['fg_pct_home'].fillna(0)
game['fg_pct_away']=game['fg_pct_away'].fillna(0)
game['fg3_pct_home']=game['fg3_pct_home'].fillna(0)
game['fg3_pct_away']=game['fg3_pct_away'].fillna(0)
game['ft_pct_home']=game['ft_pct_home'].fillna(0)
game['ft_pct_away']=game['ft_pct_away'].fillna(0)
game['pts_home']=game['pts_home'].fillna(0)
game['pts_away']=game['pts_away'].fillna(0)
game['oreb_home']=game['oreb_home'].fillna(0)
game['oreb_away']=game['oreb_away'].fillna(0)
game['dreb_home']=game['dreb_home'].fillna(0)
game['dreb_away']=game['dreb_away'].fillna(0)
game['reb_home']=game['reb_home'].fillna(0)
game['reb_away']=game['reb_away'].fillna(0)
game['ast_home']=game['ast_home'].fillna(0)
game['ast_away']=game['ast_away'].fillna(0)
game['stl_home']=game['stl_home'].fillna(0)
game['stl_away']=game['stl_away'].fillna(0)
game['blk_home']=game['blk_home'].fillna(0)
game['blk_away']=game['blk_away'].fillna(0)
game['tov_home']=game['tov_home'].fillna(0)
game['tov_away']=game['tov_away'].fillna(0)
game['pf_home']=game['pf_home'].fillna(0)
game['pf_away']=game['pf_away'].fillna(0)
game['plus_minus_home']=game['plus_minus_home'].fillna(0)
game['plus_minus_away']=game['plus_minus_away'].fillna(0)
#game['season']=game['season'].fillna(0)
game['game_id']=game['game_id'].fillna(0)
game

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,...,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away,season_type
0,21946,1610610035,HUS,Toronto Huskies,24600001,1946-11-01,HUS vs. NYK,L,0,25.0,...,0.0,0.0,0.0,0.0,0.0,0.0,68.0,2,0,Regular Season
1,21946,1610610034,BOM,St. Louis Bombers,24600003,1946-11-02,BOM vs. PIT,W,0,20.0,...,0.0,0.0,0.0,0.0,0.0,25.0,51.0,-5,0,Regular Season
2,21946,1610610032,PRO,Providence Steamrollers,24600002,1946-11-02,PRO vs. BOS,W,0,21.0,...,0.0,0.0,0.0,0.0,0.0,0.0,53.0,-6,0,Regular Season
3,21946,1610610025,CHS,Chicago Stags,24600004,1946-11-02,CHS vs. NYK,W,0,21.0,...,0.0,0.0,0.0,0.0,0.0,22.0,47.0,-16,0,Regular Season
4,21946,1610610028,DEF,Detroit Falcons,24600005,1946-11-02,DEF vs. WAS,L,0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,50.0,17,0,Regular Season
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65693,42022,1610612748,MIA,Miami Heat,42200403,2023-06-07,MIA vs. DEN,L,240,34.0,...,58.0,28.0,3.0,5.0,14.0,18.0,109.0,15,1,Playoffs
65694,42022,1610612748,MIA,Miami Heat,42200404,2023-06-09,MIA vs. DEN,L,240,35.0,...,34.0,26.0,11.0,7.0,8.0,18.0,108.0,13,1,Playoffs
65695,42022,1610612743,DEN,Denver Nuggets,42200405,2023-06-12,DEN vs. MIA,W,240,38.0,...,44.0,18.0,9.0,7.0,8.0,21.0,89.0,-5,1,Playoffs
65696,32022,1610616834,LBN,Team LeBron,32200001,2023-02-19,LBN vs. GNS,L,221,79.0,...,46.0,43.0,8.0,1.0,12.0,2.0,184.0,9,1,All-Star
65697,32022,1610616834,LBN,Team LeBron,32200001,2023-02-19,LBN vs. GNS,L,221,79.0,...,46.0,43.0,8.0,1.0,12.0,2.0,184.0,9,1,All Star

In [ ]:
#should do something with FGM (goals made), FGA (goals attempted), fg_pct (fgm/fga)
#many blanks in FGA but FGM everything is filled? (how no attempt but made?)
#fg3m series = 3 pointers
#2 blanks in wlhome and wlaway

In [ ]:
#updating data to csv
game.to_csv('game.csv', index=False)

In [ ]:
#load game_info
game_info= pd.read_csv('/content/game_info.csv')
game_info

        game_id            game_date  attendance game_time
0      24600001  1946-11-01 00:00:00         NaN       NaN
1      24600003  1946-11-02 00:00:00         NaN       NaN
2      24600002  1946-11-02 00:00:00         NaN       NaN
3      24600004  1946-11-02 00:00:00         NaN       NaN
4      24600005  1946-11-02 00:00:00         NaN       NaN
...         ...                  ...         ...       ...
58048  42200403  2023-06-07 00:00:00     20019.0      2:24
58049  42200404  2023-06-09 00:00:00     20184.0      2:29
58050  42200405  2023-06-12 00:00:00     19537.0      2:22
58051  32200001  2023-02-19 00:00:00     17886.0      0:00
58052  32200001  2023-02-19 00:00:00     17886.0      0:00

[58053 rows x 4 columns]

In [ ]:
#changing date to remove 0s
game_info['game_date']=game_info['game_date'].str.slice(0,10)
game_info

        game_id   game_date  attendance game_time
0      24600001  1946-11-01         NaN       NaN
1      24600003  1946-11-02         NaN       NaN
2      24600002  1946-11-02         NaN       NaN
3      24600004  1946-11-02         NaN       NaN
4      24600005  1946-11-02         NaN       NaN
...         ...         ...         ...       ...
58048  42200403  2023-06-07     20019.0      2:24
58049  42200404  2023-06-09     20184.0      2:29
58050  42200405  2023-06-12     19537.0      2:22
58051  32200001  2023-02-19     17886.0      0:00
58052  32200001  2023-02-19     17886.0      0:00

[58053 rows x 4 columns]

In [ ]:
#filling null with 0
game_info['attendance']=game_info['attendance'].fillna(0)
game_info['game_time']=game_info['game_time'].fillna(0)
game_info

        game_id   game_date  attendance game_time
0      24600001  1946-11-01         0.0         0
1      24600003  1946-11-02         0.0         0
2      24600002  1946-11-02         0.0         0
3      24600004  1946-11-02         0.0         0
4      24600005  1946-11-02         0.0         0
...         ...         ...         ...       ...
58048  42200403  2023-06-07     20019.0      2:24
58049  42200404  2023-06-09     20184.0      2:29
58050  42200405  2023-06-12     19537.0      2:22
58051  32200001  2023-02-19     17886.0      0:00
58052  32200001  2023-02-19     17886.0      0:00

[58053 rows x 4 columns]

In [ ]:
#updating game_info to csv
game_info.to_csv('game_info.csv', index=False)

In [ ]:
#load game_summary
game_summary= pd.read_csv('/content/game_summary.csv')
game_summary

,game_date_est,game_sequence,game_id,game_status_id,game_status_text,gamecode,home_team_id,visitor_team_id,season,live_period,live_pc_time,natl_tv_broadcaster_abbreviation,live_period_time_bcast,wh_status
0,1946-11-01 00:00:00,NaN,24600001,3,NaN,19461101/NYKHUS,1610610035,1610612752,1946,5,NaN,NaN,Q5 -,1
1,1946-11-02 00:00:00,NaN,24600003,3,NaN,19461102/PITBOM,1610610034,1610610031,1946,4,NaN,NaN,Q4 -,1
2,1946-11-02 00:00:00,NaN,24600002,3,NaN,19461102/BOSPRO,1610610032,1610612738,1946,4,NaN,NaN,Q4 -,1
3,1946-11-02 00:00:00,NaN,24600004,3,NaN,19461102/NYKCHS,1610610025,1610612752,1946,4,NaN,NaN,Q4 -,1
4,1946-11-02 00:00:00,NaN,24600005,3,NaN,19461102/WASDEF,1610610028,1610610036,1946,4,NaN,NaN,Q4 -,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58105,2023-06-07 00:00:00,1.0,42200403,3,Final,20230607/DENMIA,1610612748,1610612743,2022,4,,ABC,Q4 - ABC,1
58106,2023-06-09 00:00:00,1.0,42200404,3,Final,20230609/DENMIA,1610612748,1610612743,2022,4,,ABC,Q4 - ABC,1
58107,2023-06-12 00:00:00,1.0,42200405,3,Final,20230612/MIADEN,1610612743,1610612748,2022,4,,ABC,Q4 - ABC,1
58108,2023-02-19 00:00:00,1.0,32200001,3,Final,20230219/GNSLBN,1610616834,1610616833,2022,4,,TNT/TBS,Q4 - TNT/TBS,1
58109,2023-02-19 00:00:00,1.0,32200001,3,Final,20230219/GNSLBN,1610616834,1610616833,2022,4,,TNT/TBS,Q4 - TNT/TBS,1

In [ ]:
#change date format
game_summary['game_date_est']=game_summary['game_date_est'].str.slice(0,10)
game_summary

,game_date_est,game_sequence,game_id,game_status_id,game_status_text,gamecode,home_team_id,visitor_team_id,season,live_period,live_pc_time,natl_tv_broadcaster_abbreviation,live_period_time_bcast,wh_status
0,1946-11-01,NaN,24600001,3,NaN,19461101/NYKHUS,1610610035,1610612752,1946,5,NaN,NaN,Q5 -,1
1,1946-11-02,NaN,24600003,3,NaN,19461102/PITBOM,1610610034,1610610031,1946,4,NaN,NaN,Q4 -,1
2,1946-11-02,NaN,24600002,3,NaN,19461102/BOSPRO,1610610032,1610612738,1946,4,NaN,NaN,Q4 -,1
3,1946-11-02,NaN,24600004,3,NaN,19461102/NYKCHS,1610610025,1610612752,1946,4,NaN,NaN,Q4 -,1
4,1946-11-02,NaN,24600005,3,NaN,19461102/WASDEF,1610610028,1610610036,1946,4,NaN,NaN,Q4 -,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58105,2023-06-07,1.0,42200403,3,Final,20230607/DENMIA,1610612748,1610612743,2022,4,,ABC,Q4 - ABC,1
58106,2023-06-09,1.0,42200404,3,Final,20230609/DENMIA,1610612748,1610612743,2022,4,,ABC,Q4 - ABC,1
58107,2023-06-12,1.0,42200405,3,Final,20230612/MIADEN,1610612743,1610612748,2022,4,,ABC,Q4 - ABC,1
58108,2023-02-19,1.0,32200001,3,Final,20230219/GNSLBN,1610616834,1610616833,2022,4,,TNT/TBS,Q4 - TNT/TBS,1
58109,2023-02-19,1.0,32200001,3,Final,20230219/GNSLBN,1610616834,1610616833,2022,4,,TNT/TBS,Q4 - TNT/TBS,1

In [ ]:
#changing null int to 0
game_summary['game_sequence']=game_summary['game_sequence'].fillna(0)
game_summary['game_status_text']
#change quarter text to 'Q5' if 'Q5 -'
game_summary['live_period_time_bcast']=game_summary['live_period_time_bcast'].str.rstrip(' -')
game_summary

,game_date_est,game_sequence,game_id,game_status_id,game_status_text,gamecode,home_team_id,visitor_team_id,season,live_period,live_pc_time,natl_tv_broadcaster_abbreviation,live_period_time_bcast,wh_status
0,1946-11-01,0.0,24600001,3,NaN,19461101/NYKHUS,1610610035,1610612752,1946,5,NaN,NaN,Q5,1
1,1946-11-02,0.0,24600003,3,NaN,19461102/PITBOM,1610610034,1610610031,1946,4,NaN,NaN,Q4,1
2,1946-11-02,0.0,24600002,3,NaN,19461102/BOSPRO,1610610032,1610612738,1946,4,NaN,NaN,Q4,1
3,1946-11-02,0.0,24600004,3,NaN,19461102/NYKCHS,1610610025,1610612752,1946,4,NaN,NaN,Q4,1
4,1946-11-02,0.0,24600005,3,NaN,19461102/WASDEF,1610610028,1610610036,1946,4,NaN,NaN,Q4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58105,2023-06-07,1.0,42200403,3,Final,20230607/DENMIA,1610612748,1610612743,2022,4,,ABC,Q4 - ABC,1
58106,2023-06-09,1.0,42200404,3,Final,20230609/DENMIA,1610612748,1610612743,2022,4,,ABC,Q4 - ABC,1
58107,2023-06-12,1.0,42200405,3,Final,20230612/MIADEN,1610612743,1610612748,2022,4,,ABC,Q4 - ABC,1
58108,2023-02-19,1.0,32200001,3,Final,20230219/GNSLBN,1610616834,1610616833,2022,4,,TNT/TBS,Q4 - TNT/TBS,1
58109,2023-02-19,1.0,32200001,3,Final,20230219/GNSLBN,1610616834,1610616833,2022,4,,TNT/TBS,Q4 - TNT/TBS,1

In [ ]:
#update to csv
game_summary.to_csv('game_summary.csv', index=False)

In [ ]:
#load team data
#no changes were nessesary
team= pd.read_csv('/content/team.csv')
team

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Atlanta,1949.0
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946.0
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970.0
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002.0
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966.0
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980.0
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976.0
7,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946.0
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967.0
9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970.0
10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948.0
11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988.0
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968.0
13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989.0
14,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976.0
15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946.0
16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989.0
17,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976.0
18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949.0
19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968.0
20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970.0
21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948.0
22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976.0
23,1610612760,Oklahoma City Thunder,OKC,Thunder,Oklahoma City,Oklahoma,1967.0
24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995.0
25,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974.0
26,1610612763,Memphis Grizzlies,MEM,Grizzlies,Memphis,Tennessee,1995.0
27,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961.0
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948.0
29,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988.0

In [ ]:
#load team details
team_details= pd.read_csv('/content/team_details.csv')
team_details

,team_id,abbreviation,nickname,yearfounded,city,arena,arenacapacity,owner,generalmanager,headcoach,dleagueaffiliation,facebook,instagram,twitter
0,1610612737,ATL,Hawks,1949.0,Atlanta,State Farm Arena,18729.0,Tony Ressler,Travis Schlenk,Quin Snyder,College Park Skyhawks,https://www.facebook.com/hawks,https://instagram.com/atlhawks,https://twitter.com/ATLHawks
1,1610612741,CHI,Bulls,1966.0,Chicago,United Center,21711.0,Michael Reinsdorf,Arturas Karnisovas,Billy Donovan,Windy City Bulls,https://www.facebook.com/chicagobulls,https://instagram.com/chicagobulls,https://twitter.com/chicagobulls
2,1610612742,DAL,Mavericks,1980.0,Dallas,American Airlines Center,19200.0,Mark Cuban,Nico Harrison,Jason Kidd,Texas Legends,https://www.facebook.com/dallasmavs,https://instagram.com/dallasmavs,https://twitter.com/dallasmavs
3,1610612743,DEN,Nuggets,1976.0,Denver,Ball Arena,NaN,Stan Kroenke,Calvin Booth,Michael Malone,Grand Rapids Gold,https://www.facebook.com/DenverNuggets,https://instagram.com/nuggets,https://twitter.com/nuggets
4,1610612744,GSW,Warriors,1946.0,Golden State,Chase Center,NaN,Joe Lacob,Bob Myers,Steve Kerr,Santa Cruz Warriors,https://www.facebook.com/warriors,https://instagram.com/warriors,https://twitter.com/warriors
5,1610612745,HOU,Rockets,1967.0,Houston,Toyota Center,18104.0,Tilman Fertitta,Rafael Stone,Ime Udoka,Rio Grande Valley Vipers,https://www.facebook.com/houstonrockets,https://instagram.com/houstonrockets,https://twitter.com/HoustonRockets
6,1610612746,LAC,Clippers,1970.0,Los Angeles,Crypto.com Arena,19060.0,Steve Ballmer,Michael Winger,Tyronn Lue,Agua Caliente Clippers of Ontario,https://www.facebook.com/LAClippers,https://instagram.com/laclippers,https://twitter.com/LAClippers
7,1610612747,LAL,Lakers,1948.0,Los Angeles,Crypto.com Arena,19060.0,Jeanie Buss,Rob Pelinka,Darvin Ham,South Bay Lakers,https://www.facebook.com/losangeleslakers,https://instagram.com/lakers,https://twitter.com/Lakers
8,1610612748,MIA,Heat,1988.0,Miami,Kaseya Center,19600.0,Micky Arison,Pat Riley,Erik Spoelstra,Sioux Falls Skyforce,https://www.facebook.com/MiamiHeat,https://instagram.com/miamiheat,https://twitter.com/MiamiHEAT
9,1610612749,MIL,Bucks,1968.0,Milwaukee,Fiserv Forum,17500.0,Wesley Edens & Marc Lasry,Jon Horst,Adrian Griffin,Wisconsin Herd,https://www.facebook.com/milwaukeebucks,https://instagram.com/bucks,https://twitter.com/Bucks
10,1610612750,MIN,Timberwolves,1989.0,Minnesota,Target Center,19356.0,Glen Taylor,Tim Connelly,Chris Finch,Iowa Wolves,https://www.facebook.com/MNTimberwolves,https://instagram.com/timberwolves,https://twitter.com/Timberwolves
11,1610612751,BKN,Nets,1976.0,Brooklyn,Barclays Center,NaN,Joe Tsai,Sean Marks,Jacque Vaughn,Long Island Nets,https://www.facebook.com/BrooklynNets,https://instagram.com/brooklynnets,https://twitter.com/BrooklynNets
12,1610612754,IND,Pacers,1976.0,Indiana,Gainbridge Fieldhouse,18345.0,Herb Simon,Kevin Pritchard,Rick Carlisle,Fort Wayne Mad Ants,https://www.facebook.com/pacers,https://instagram.com/pacers,https://twitter.com/Pacers
13,1610612755,PHI,76ers,1949.0,Philadelphia,Wells Fargo Center,NaN,Joshua Harris & David Blitzer,Elton Brand,Nick Nurse,Delaware Blue Coats,https://www.facebook.com/Sixers,https://instagram.com/sixers,https://twitter.com/Sixers
14,1610612756,PHX,Suns,1968.0,Phoenix,Footprint Center,NaN,Mat Ishbia,James Jones,Frank Vogel,No Affiliate,https://www.facebook.com/suns,https://instagram.com/suns,https://twitter.com/Suns
15,1610612757,POR,Trail Blazers,1970.0,Portland,Moda Center,19980.0,Jody Allen,Joe Cronin,Chauncey Billups,No Affiliate,https://www.facebook.com/trailblazers,https://instagram.com/trailblazers,https://twitter.com/trailblazers
16,1610612758,SAC,Kings,1948.0,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Monte McNair,Mike Brown,Stockton Kings,https://www.facebook.com/sacramentokings,https://instagram.com/sacramentokings,https://twitter.com/SacramentoKings
17,1610612759,SAS,Spurs,1976.0,San Antonio,AT&T Center,18694.0,Peter Holt,Brian Wright,Gregg Popovich,Austin Spurs,https://www.facebook.com/Spurs,https://instagram.com/spurs,https://twitter.com/spurs
18,1610612760,OKC,Thunder,1967.0,Oklahoma City,Paycom Center,NaN,Clay Bennett,Sam Presti,Mark Daigneault,Oklahoma City Blue,https://www.facebook.com/OKCThunder,https://instagram.com/okcthunder,https://twitter.com/okcthunder
19,1610612761,TOR,Raptors,1995.0,Toronto,Scotiabank Arena,NaN,Lawrence Tanenbaum,Masai Ujiri,NaN,Raptors 905,https://www.facebook.com/TorontoRaptors,https://instagram.com/raptors,https://twitter.com/Raptors
20,1610612762,UTA,Jazz,1974.0,Utah,Delta Center,NaN,Ryan Smith,Justin Zanik,Will Hardy,Salt Lake City Stars,https://www.facebook.com/utahjazz,https://instagram.com/utahjazz,https://twitter.com/utahjazz
21,1610612763,MEM,Grizzlies,1995.0,Memphis,FedExForum,18119.0,Robert Pera,Zach Kleiman,Taylor Jenkins,Memphis Hustle,https://www.facebook.com/MemphisGrizzlies,https://instagram.com/memgrizz,https://twitter.com/memgrizz
22,1610612764,WAS,Wizards,1961.0,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Wes Unseld,Capital City Go-Go,https://www.facebook.com/Wizards,https://instagram.com/washwizards,https://twitter.com/WashWizards
23,1610612765,DET,Pistons,1948.0,Detroit,Little Caesars Arena,NaN,Tom Gores,Ed Stefanski,Monty Williams,Motor City Cruise,https://www.facebook.com/detroitpistons,https://instagram.com/detroitpistons,https://twitter.com/DetroitPistons
24,1610612766,CHA,Hornets,1988.0,Charlotte,Spectrum Center,19026.0,Michael Jordan,Mitch Kupchak,Steve Clifford,Greensboro Swarm,https://www.facebook.com/hornets,https://instagram.com/hornets,https://twitter.com/hornets

In [ ]:
#load team history
team_history= pd.read_csv('/content/team_history.csv')
team_history

,team_id,city,nickname,year_founded,year_active_till
0,1610612737,Atlanta,Hawks,1968,2019
1,1610612737,St. Louis,Hawks,1955,1967
2,1610612737,Milwaukee,Hawks,1951,1954
3,1610612737,Tri-Cities,Blackhawks,1949,1950
4,1610612741,Chicago,Bulls,1966,2019
5,1610612742,Dallas,Mavericks,1980,2019
6,1610612743,Denver,Nuggets,1976,2019
7,1610612744,Golden State,Warriors,1971,2019
8,1610612744,San Francisco,Warriors,1962,1970
9,1610612744,Philadelphia,Warriors,1946,1961
10,1610612745,Houston,Rockets,1971,2019
11,1610612745,San Diego,Rockets,1967,1970
12,1610612746,Los Angeles,Clippers,1984,2019
13,1610612746,San Diego,Clippers,1978,1983
14,1610612746,Buffalo,Braves,1970,1977
15,1610612747,Los Angeles,Lakers,1960,2019
16,1610612747,Minneapolis,Lakers,1948,1959
17,1610612748,Miami,Heat,1988,2019
18,1610612749,Milwaukee,Bucks,1968,2019
19,1610612750,Minnesota,Timberwolves,1989,2019
20,1610612751,Brooklyn,Nets,2012,2019
21,1610612751,New Jersey,Nets,1977,2011
22,1610612751,New York,Nets,1976,1976
23,1610612754,Indiana,Pacers,1976,2019
24,1610612755,Philadelphia,76ers,1963,2019
25,1610612755,Syracuse,Nationals,1949,1962
26,1610612756,Phoenix,Suns,1968,2019
27,1610612757,Portland,Trail Blazers,1970,2019
28,1610612758,Sacramento,Kings,1985,2019
29,1610612758,Kansas City,Kings,1975,1984
30,1610612758,Kansas City-Omaha,Kings,1972,1974
31,1610612758,Cincinnati,Royals,1957,1971
32,1610612758,Rochester,Royals,1948,1956
33,1610612759,San Antonio,Spurs,1976,2019
34,1610612760,Oklahoma City,Thunder,2008,2019
35,1610612760,Seattle,SuperSonics,1967,2007
36,1610612761,Toronto,Raptors,1995,2019
37,1610612762,Utah,Jazz,1979,2019
38,1610612762,New Orleans,Jazz,1974,1978
39,1610612763,Memphis,Grizzlies,2001,2019
40,1610612763,Vancouver,Grizzlies,1995,2000
41,1610612764,Washington,Wizards,1997,2019
42,1610612764,Washington,Bullets,1974,1996
43,1610612764,Capital,Bullets,1973,1973
44,1610612764,Baltimore,Bullets,1963,1972
45,1610612764,Chicago,Zephyrs,1962,1962
46,1610612764,Chicago,Packers,1961,1961
47,1610612765,Detroit,Pistons,1957,2019
48,1610612765,Ft. Wayne Zollner,Pistons,1948,1956
49,1610612766,Charlotte,Hornets,2014,2019
50,1610612766,Charlotte,Bobcats,2004,2013
51,1610612766,Charlotte,Hornets,1988,2001

In [ ]:
#load team_info_common
team_info_common= pd.read_csv('/content/team_info_common.csv')
team_info_common

Empty DataFrame
Columns: [team_id, season_year, team_city, team_name, team_abbreviation, team_conference, team_division, team_code, team_slug, w, l, pct, conf_rank, div_rank, min_year, max_year, league_id, season_id, pts_rank, pts_pg, reb_rank, reb_pg, ast_rank, ast_pg, opp_pts_rank, opp_pts_pg]
Index: []

[0 rows x 26 columns]

In [ ]:
#load draft_history
draft_history= pd.read_csv('/content/draft_history.csv')
draft_history

,person_id,player_name,season,round_number,round_pick,overall_pick,draft_type,team_id,team_city,team_name,team_abbreviation,organization,organization_type,player_profile_flag
0,79299,Clifton McNeeley,1947,1,1,1,Draft,1610610031,Pittsburgh,Ironmen,PIT,Texas-El Paso,College/University,0
1,78109,Glen Selbo,1947,1,2,2,Draft,1610610035,Toronto,Huskies,HUS,Wisconsin,College/University,1
2,76649,Eddie Ehlers,1947,1,3,3,Draft,1610612738,Boston,Celtics,BOS,Purdue,College/University,1
3,79302,Walt Dropo,1947,1,4,4,Draft,1610610032,Providence,Steamrollers,PRO,Connecticut,College/University,0
4,77048,Dick Holub,1947,1,5,5,Draft,1610612752,New York,Knicks,NYK,Long Island-Brooklyn,College/University,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7985,1641771,Jalen Slawson,2023,2,24,54,Draft,1610612758,Sacramento,Kings,SAC,Furman,College/University,1
7986,1631209,Isaiah Wong,2023,2,25,55,Draft,1610612754,Indiana,Pacers,IND,Miami (FL),College/University,1
7987,1641844,Tarik Biberovic,2023,2,26,56,Draft,1610612763,Memphis,Grizzlies,MEM,Fenerbahce S.K. (Turkey),Other Team/Club,1
7988,1631218,Trayce Jackson-Davis,2023,2,27,57,Draft,1610612764,Washington,Wizards,WAS,Indiana,College/University,1
7989,1641753,Chris Livingston,2023,2,28,58,Draft,1610612749,Milwaukee,Bucks,MIL,Kentucky,College/University,1

In [ ]:
#load draft_combine_stats
draft_combine_stats= pd.read_csv('/content/draft_combine_stats.csv')
draft_combine_stats

,season,player_id,first_name,last_name,player_name,position,height_wo_shoes,height_wo_shoes_ft_in,height_w_shoes,height_w_shoes_ft_in,...,spot_nba_break_right,spot_nba_corner_right,off_drib_fifteen_break_left,off_drib_fifteen_top_key,off_drib_fifteen_break_right,off_drib_college_break_left,off_drib_college_top_key,off_drib_college_break_right,on_move_fifteen,on_move_college
0,2001,12033,Adam,Allenspach,Adam Allenspach,C,83.50,6' 11.5'',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2001,2240,Gilbert,Arenas,Gilbert Arenas,SG,74.25,6' 2.25'',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2001,2220,Brandon,Armstrong,Brandon Armstrong,SG,75.50,6' 3.5'',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2001,2203,Shane,Battier,Shane Battier,SF-PF,80.25,6' 8.25'',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2001,12034,Cookie,Belcher,Cookie Belcher,SG-PG,75.00,6' 3'',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1197,2023,1641705,Victor,Wembanyama,Victor Wembanyama,C,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1198,2023,1641727,Dariq,Whitehead,Dariq Whitehead,SG,77.75,6' 5.75'',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1199,2023,1641715,Cam,Whitmore,Cam Whitmore,SF,77.75,6' 5.75'',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1200,2023,1630592,Jalen,Wilson,Jalen Wilson,SF,77.50,6' 5.50'',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,18-30,NaN,NaN,NaN,14-25
1201,2023,1631209,Isaiah,Wong,Isaiah Wong,SG,74.50,6' 2.50'',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,23-30,NaN,NaN,NaN,17-25

In [ ]:
file_columns = {}

file_names = ['game', 'game_info', 'game_summary', 'team', 'team_details', 'team_history', 'team_info_common', 'draft_history', 'draft_combine_stats']

for file_name in file_names:
  df = pd.read_csv(f'/content/{file_name}.csv')
  file_columns[file_name] = df.columns.tolist()

common_columns = {}
for file1 in file_columns:
  for file2 in file_columns:
    if file1 != file2:
      common = set(file_columns[file1]).intersection(file_columns[file2])
      if common:
        key = tuple(sorted((file1, file2)))
        if key not in common_columns:
          common_columns[key] = common

for (file1, file2), columns in common_columns.items():
  print(f"Common columns between {file1} and {file2}: {', '.join(columns)}")

Common columns between game and game_info: game_id, game_date
Common columns between game and game_summary: game_id
Common columns between game and team_info_common: season_id
Common columns between game_info and game_summary: game_id
Common columns between draft_history and game_summary: season
Common columns between draft_combine_stats and game_summary: season
Common columns between team and team_details: nickname, abbreviation, city
Common columns between team and team_history: nickname, year_founded, city
Common columns between team_details and team_history: nickname, team_id, city
Common columns between team_details and team_info_common: team_id
Common columns between draft_history and team_details: team_id
Common columns between team_history and team_info_common: team_id
Common columns between draft_history and team_history: team_id
Common columns between draft_history and team_info_common: team_abbreviation, team_id, team_city, team_name
Common columns between draft_combine_stats and draft_history: player_name, season

In [ ]:

# Create a dictionary to store the DataFrames
dfs = {}
for file_name in file_names:
  dfs[file_name] = pd.read_csv(f'/content/{file_name}.csv')

# Iterate over the common_columns dictionary and merge DataFrames
for (file1, file2), columns in common_columns.items():
  if len(columns) > 0:
    merged_df = pd.merge(dfs[file1], dfs[file2], on=list(columns), how='inner')
    print(f"Merged {file1} and {file2} on columns: {', '.join(columns)}")
    print(merged_df.head())

Merged game and game_info on columns: game_id, game_date
   season_id  team_id_home team_abbreviation_home           team_name_home  \
0      21946    1610610035                    HUS          Toronto Huskies
1      21946    1610610034                    BOM        St. Louis Bombers
2      21946    1610610032                    PRO  Providence Steamrollers
3      21946    1610610025                    CHS            Chicago Stags
4      21946    1610610028                    DEF          Detroit Falcons

    game_id   game_date matchup_home wl_home  min  fgm_home  ...  stl_away  \
0  24600001  1946-11-01  HUS vs. NYK       L    0      25.0  ...       0.0
1  24600003  1946-11-02  BOM vs. PIT       W    0      20.0  ...       0.0
2  24600002  1946-11-02  PRO vs. BOS       W    0      21.0  ...       0.0
3  24600004  1946-11-02  CHS vs. NYK       W    0      21.0  ...       0.0
4  24600005  1946-11-02  DEF vs. WAS       L    0      10.0  ...       0.0

   blk_away  tov_away  pf_away  pts_away  plus_minus_away  \
0       0.0       0.0      0.0      68.0                2
1       0.0       0.0     25.0      51.0               -5
2       0.0       0.0      0.0      53.0               -6
3       0.0       0.0     22.0      47.0              -16
4       0.0       0.0      0.0      50.0               17

   video_available_away     season_type  attendance  game_time
0                     0  Regular Season         0.0          0
1                     0  Regular Season         0.0          0
2                     0  Regular Season         0.0          0
3                     0  Regular Season         0.0          0
4                     0  Regular Season         0.0          0

[5 rows x 57 columns]
Merged game and game_summary on columns: game_id
   season_id  team_id_home team_abbreviation_home           team_name_home  \
0      21946    1610610035                    HUS          Toronto Huskies
1      21946    1610610034                    BOM        St. Louis Bombers
2      21946    1610610032                    PRO  Providence Steamrollers
3      21946    1610610025                    CHS            Chicago Stags
4      21946    1610610028                    DEF          Detroit Falcons

    game_id   game_date matchup_home wl_home  min  fgm_home  ...  \
0  24600001  1946-11-01  HUS vs. NYK       L    0      25.0  ...
1  24600003  1946-11-02  BOM vs. PIT       W    0      20.0  ...
2  24600002  1946-11-02  PRO vs. BOS       W    0      21.0  ...
3  24600004  1946-11-02  CHS vs. NYK       W    0      21.0  ...
4  24600005  1946-11-02  DEF vs. WAS       L    0      10.0  ...

   game_status_text         gamecode  home_team_id  visitor_team_id  season  \
0               NaN  19461101/NYKHUS    1610610035       1610612752    1946
1               NaN  19461102/PITBOM    1610610034       1610610031    1946
2               NaN  19461102/BOSPRO    1610610032       1610612738    1946
3               NaN  19461102/NYKCHS    1610610025       1610612752    1946
4               NaN  19461102/WASDEF    1610610028       1610610036    1946

   live_period  live_pc_time  natl_tv_broadcaster_abbreviation  \
0            5           NaN                               NaN
1            4           NaN                               NaN
2            4           NaN                               NaN
3            4           NaN                               NaN
4            4           NaN                               NaN

   live_period_time_bcast  wh_status
0                      Q5          1
1                      Q4          1
2                      Q4          1
3                      Q4          1
4                      Q4          1

[5 rows x 68 columns]
Merged game and team_info_common on columns: season_id
Empty DataFrame
Columns: [season_id, team_id_home, team_abbreviation_home, team_name_home, game_id, game_date, matchup_home, wl_home, min, fgm_home, fga_home, fg_pct_home, fg3m_home, fg3a_home, fg3_pct_home, ftm_home, fta_home, ft_pct_home, oreb_home, dreb_home, reb_home, ast_home, stl_home, blk_home, tov_home, pf_home, pts_home, plus_minus_home, video_available_home, team_id_away, team_abbreviation_away, team_name_away, matchup_away, wl_away, fgm_away, fga_away, fg_pct_away, fg3m_away, fg3a_away, fg3_pct_away, ftm_away, fta_away, ft_pct_away, oreb_away, dreb_away, reb_away, ast_away, stl_away, blk_away, tov_away, pf_away, pts_away, plus_minus_away, video_available_away, season_type, team_id, season_year, team_city, team_name, team_abbreviation, team_conference, team_division, team_code, team_slug, w, l, pct, conf_rank, div_rank, min_year, max_year, league_id, pts_rank, pts_pg, reb_rank, reb_pg, ast_rank, ast_pg, opp_pts_rank, opp_pts_pg]
Index: []

[0 rows x 80 columns]
Merged game_info and game_summary on columns: game_id
    game_id   game_date  attendance game_time game_date_est  game_sequence  \
0  24600001  1946-11-01         0.0         0    1946-11-01            0.0
1  24600003  1946-11-02         0.0         0    1946-11-02            0.0
2  24600002  1946-11-02         0.0         0    1946-11-02            0.0
3  24600004  1946-11-02         0.0         0    1946-11-02            0.0
4  24600005  1946-11-02         0.0         0    1946-11-02            0.0

   game_status_id game_status_text         gamecode  home_team_id  \
0               3              NaN  19461101/NYKHUS    1610610035
1               3              NaN  19461102/PITBOM    1610610034
2               3              NaN  19461102/BOSPRO    1610610032
3               3              NaN  19461102/NYKCHS    1610610025
4               3              NaN  19461102/WASDEF    1610610028

   visitor_team_id  season  live_period live_pc_time  \
0       1610612752    1946            5          NaN
1       1610610031    1946            4          NaN
2       1610612738    1946            4          NaN
3       1610612752    1946            4          NaN
4       1610610036    1946            4          NaN

  natl_tv_broadcaster_abbreviation live_period_time_bcast  wh_status
0                              NaN                     Q5          1
1                              NaN                     Q4          1
2                              NaN                     Q4          1
3                              NaN                     Q4          1
4                              NaN                     Q4          1
Merged draft_history and game_summary on columns: season
   person_id       player_name  season  round_number  round_pick  \
0      79299  Clifton McNeeley    1947             1           1
1      79299  Clifton McNeeley    1947             1           1
2      79299  Clifton McNeeley    1947             1           1
3      79299  Clifton McNeeley    1947             1           1
4      79299  Clifton McNeeley    1947             1           1

   overall_pick draft_type     team_id   team_city team_name  ...  \
0             1      Draft  1610610031  Pittsburgh   Ironmen  ...
1             1      Draft  1610610031  Pittsburgh   Ironmen  ...
2             1      Draft  1610610031  Pittsburgh   Ironmen  ...
3             1      Draft  1610610031  Pittsburgh   Ironmen  ...
4             1      Draft  1610610031  Pittsburgh   Ironmen  ...

  game_status_id game_status_text         gamecode  home_team_id  \
0              3              NaN  19471112/BALWAS    1610610036
1              3              NaN  19471113/PROPHW    1610612744
2              3              NaN  19471113/BOSBAL    1610610024
3              3              NaN  19471113/WASNYK    1610612752
4              3              NaN  19471114/PHWBOS    1610612738

  visitor_team_id  live_period  live_pc_time  \
0      1610610024            4           NaN
1      1610610032            4           NaN
2      1610612738            4           NaN
3      1610610036            4           NaN
4      1610612744            4           NaN

   natl_tv_broadcaster_abbreviation live_period_time_bcast wh_status
0                               NaN                     Q4         1
1                               NaN                     Q4         1
2                               NaN                     Q4         1
3                               NaN                     Q4         1
4                               NaN                     Q4         1

[5 rows x 27 columns]
Merged draft_combine_stats and game_summary on columns: season
   season  player_id first_name   last_name      player_name position  \
0    2001      12033       Adam  Allenspach  Adam Allenspach        C
1    2001      12033       Adam  Allenspach  Adam Allenspach        C
2    2001      12033       Adam  Allenspach  Adam Allenspach        C
3    2001      12033       Adam  Allenspach  Adam Allenspach        C
4    2001      12033       Adam  Allenspach  Adam Allenspach        C

   height_wo_shoes height_wo_shoes_ft_in  height_w_shoes height_w_shoes_ft_in  \
0             83.5             6' 11.5''             NaN                  NaN
1             83.5             6' 11.5''             NaN                  NaN
2             83.5             6' 11.5''             NaN                  NaN
3             83.5             6' 11.5''             NaN                  NaN
4             83.5             6' 11.5''             NaN                  NaN

   ...  game_status_id  game_status_text         gamecode  home_team_id  \
0  ...               3             Final  20011030/PHIMIN    1610612750
1  ...               3             Final  20011030/PORLAL    1610612747
2  ...               3             Final  20011030/TORORL    1610612753
3  ...               3             Final  20011030/ATLHOU    1610612745
4  ...               3             Final  20011030/WASNYK    1610612752

  visitor_team_id  live_period  live_pc_time  \
0      1610612755            4           NaN
1      1610612757            4           NaN
2      1610612761            4           NaN
3      1610612737            5           NaN
4      1610612764            4           NaN

   natl_tv_broadcaster_abbreviation  live_period_time_bcast  wh_status
0                               NaN                      Q4          1
1                               NaN                      Q4          1
2                               NaN                      Q4          1
3                               NaN                      Q5          1
4                               NaN                      Q4          1

[5 rows x 60 columns]
Merged team and team_details on columns: nickname, abbreviation, city
           id              full_name abbreviation   nickname          city  \
0  1610612737          Atlanta Hawks          ATL      Hawks       Atlanta
1  1610612741          Chicago Bulls          CHI      Bulls       Chicago
2  1610612742       Dallas Mavericks          DAL  Mavericks        Dallas
3  1610612743         Denver Nuggets          DEN    Nuggets        Denver
4  1610612744  Golden State Warriors          GSW   Warriors  Golden State

        state  year_founded     team_id  yearfounded  \
0     Atlanta        1949.0  1610612737       1949.0
1    Illinois        1966.0  1610612741       1966.0
2       Texas        1980.0  1610612742       1980.0
3    Colorado        1976.0  1610612743       1976.0
4  California        1946.0  1610612744       1946.0

                      arena  arenacapacity              owner  \
0          State Farm Arena        18729.0       Tony Ressler
1             United Center        21711.0  Michael Reinsdorf
2  American Airlines Center        19200.0         Mark Cuban
3                Ball Arena            NaN       Stan Kroenke
4              Chase Center            NaN          Joe Lacob

       generalmanager       headcoach     dleagueaffiliation  \
0      Travis Schlenk     Quin Snyder  College Park Skyhawks
1  Arturas Karnisovas   Billy Donovan       Windy City Bulls
2       Nico Harrison      Jason Kidd          Texas Legends
3        Calvin Booth  Michael Malone      Grand Rapids Gold
4           Bob Myers      Steve Kerr    Santa Cruz Warriors

                                 facebook                           instagram  \
0          https://www.facebook.com/hawks      https://instagram.com/atlhawks
1   https://www.facebook.com/chicagobulls  https://instagram.com/chicagobulls
2     https://www.facebook.com/dallasmavs    https://instagram.com/dallasmavs
3  https://www.facebook.com/DenverNuggets       https://instagram.com/nuggets
4       https://www.facebook.com/warriors      https://instagram.com/warriors

                            twitter
0      https://twitter.com/ATLHawks
1  https://twitter.com/chicagobulls
2    https://twitter.com/dallasmavs
3       https://twitter.com/nuggets
4      https://twitter.com/warriors
Merged team and team_history on columns: nickname, year_founded, city
           id         full_name abbreviation   nickname       city      state  \
0  1610612741     Chicago Bulls          CHI      Bulls    Chicago   Illinois
1  1610612742  Dallas Mavericks          DAL  Mavericks     Dallas      Texas
2  1610612743    Denver Nuggets          DEN    Nuggets     Denver   Colorado
3  1610612748        Miami Heat          MIA       Heat      Miami    Florida
4  1610612749   Milwaukee Bucks          MIL      Bucks  Milwaukee  Wisconsin

   year_founded     team_id  year_active_till
0        1966.0  1610612741              2019
1        1980.0  1610612742              2019
2        1976.0  1610612743              2019
3        1988.0  1610612748              2019
4        1968.0  1610612749              2019
Merged team_details and team_history on columns: nickname, team_id, city
      team_id abbreviation   nickname  yearfounded          city  \
0  1610612737          ATL      Hawks       1949.0       Atlanta
1  1610612741          CHI      Bulls       1966.0       Chicago
2  1610612742          DAL  Mavericks       1980.0        Dallas
3  1610612743          DEN    Nuggets       1976.0        Denver
4  1610612744          GSW   Warriors       1946.0  Golden State

                      arena  arenacapacity              owner  \
0          State Farm Arena        18729.0       Tony Ressler
1             United Center        21711.0  Michael Reinsdorf
2  American Airlines Center        19200.0         Mark Cuban
3                Ball Arena            NaN       Stan Kroenke
4              Chase Center            NaN          Joe Lacob

       generalmanager       headcoach     dleagueaffiliation  \
0      Travis Schlenk     Quin Snyder  College Park Skyhawks
1  Arturas Karnisovas   Billy Donovan       Windy City Bulls
2       Nico Harrison      Jason Kidd          Texas Legends
3        Calvin Booth  Michael Malone      Grand Rapids Gold
4           Bob Myers      Steve Kerr    Santa Cruz Warriors

                                 facebook                           instagram  \
0          https://www.facebook.com/hawks      https://instagram.com/atlhawks
1   https://www.facebook.com/chicagobulls  https://instagram.com/chicagobulls
2     https://www.facebook.com/dallasmavs    https://instagram.com/dallasmavs
3  https://www.facebook.com/DenverNuggets       https://instagram.com/nuggets
4       https://www.facebook.com/warriors      https://instagram.com/warriors

                            twitter  year_founded  year_active_till
0      https://twitter.com/ATLHawks          1968              2019
1  https://twitter.com/chicagobulls          1966              2019
2    https://twitter.com/dallasmavs          1980              2019
3       https://twitter.com/nuggets          1976              2019
4      https://twitter.com/warriors          1971              2019
Merged team_details and team_info_common on columns: team_id
Empty DataFrame
Columns: [team_id, abbreviation, nickname, yearfounded, city, arena, arenacapacity, owner, generalmanager, headcoach, dleagueaffiliation, facebook, instagram, twitter, season_year, team_city, team_name, team_abbreviation, team_conference, team_division, team_code, team_slug, w, l, pct, conf_rank, div_rank, min_year, max_year, league_id, season_id, pts_rank, pts_pg, reb_rank, reb_pg, ast_rank, ast_pg, opp_pts_rank, opp_pts_pg]
Index: []

[0 rows x 39 columns]
Merged draft_history and team_details on columns: team_id
   person_id      player_name  season  round_number  round_pick  overall_pick  \
0      76479  Francis Crossin    1947             1           6             6
1      79292      Norman Butz    1947             0           0             0
2      79293      Jim Kaeding    1947             0           0             0
3      79294  Ed Koffenberger    1947             0           0             0
4      77918          Don Ray    1948             1          11            11

  draft_type     team_id     team_city team_name  ...          city  \
0      Draft  1610612744  Philadelphia  Warriors  ...  Golden State
1      Draft  1610612744  Philadelphia  Warriors  ...  Golden State
2      Draft  1610612744  Philadelphia  Warriors  ...  Golden State
3      Draft  1610612744  Philadelphia  Warriors  ...  Golden State
4      Draft  1610612744  Philadelphia  Warriors  ...  Golden State

          arena arenacapacity      owner generalmanager   headcoach  \
0  Chase Center           NaN  Joe Lacob      Bob Myers  Steve Kerr
1  Chase Center           NaN  Joe Lacob      Bob Myers  Steve Kerr
2  Chase Center           NaN  Joe Lacob      Bob Myers  Steve Kerr
3  Chase Center           NaN  Joe Lacob      Bob Myers  Steve Kerr
4  Chase Center           NaN  Joe Lacob      Bob Myers  Steve Kerr

    dleagueaffiliation                           facebook  \
0  Santa Cruz Warriors  https://www.facebook.com/warriors
1  Santa Cruz Warriors  https://www.facebook.com/warriors
2  Santa Cruz Warriors  https://www.facebook.com/warriors
3  Santa Cruz Warriors  https://www.facebook.com/warriors
4  Santa Cruz Warriors  https://www.facebook.com/warriors

                        instagram                       twitter
0  https://instagram.com/warriors  https://twitter.com/warriors
1  https://instagram.com/warriors  https://twitter.com/warriors
2  https://instagram.com/warriors  https://twitter.com/warriors
3  https://instagram.com/warriors  https://twitter.com/warriors
4  https://instagram.com/warriors  https://twitter.com/warriors

[5 rows x 27 columns]
Merged team_history and team_info_common on columns: team_id
Empty DataFrame
Columns: [team_id, city, nickname, year_founded, year_active_till, season_year, team_city, team_name, team_abbreviation, team_conference, team_division, team_code, team_slug, w, l, pct, conf_rank, div_rank, min_year, max_year, league_id, season_id, pts_rank, pts_pg, reb_rank, reb_pg, ast_rank, ast_pg, opp_pts_rank, opp_pts_pg]
Index: []

[0 rows x 30 columns]
Merged draft_history and team_history on columns: team_id
   person_id      player_name  season  round_number  round_pick  overall_pick  \
0      76479  Francis Crossin    1947             1           6             6
1      76479  Francis Crossin    1947             1           6             6
2      76479  Francis Crossin    1947             1           6             6
3      79292      Norman Butz    1947             0           0             0
4      79292      Norman Butz    1947             0           0             0

  draft_type     team_id     team_city team_name team_abbreviation  \
0      Draft  1610612744  Philadelphia  Warriors               PHW
1      Draft  1610612744  Philadelphia  Warriors               PHW
2      Draft  1610612744  Philadelphia  Warriors               PHW
3      Draft  1610612744  Philadelphia  Warriors               PHW
4      Draft  1610612744  Philadelphia  Warriors               PHW

     organization   organization_type  player_profile_flag           city  \
0    Pennsylvania  College/University                    1   Golden State
1    Pennsylvania  College/University                    1  San Francisco
2    Pennsylvania  College/University                    1   Philadelphia

In [ ]:
merged_files = []
for (file1, file2), columns in common_columns.items():
  if len(columns) > 0:
    merged_df = pd.merge(dfs[file1], dfs[file2], on=list(columns), how='inner')
    new_file_name = f"{file1}_{file2}_merged.csv"
    merged_df.to_csv(new_file_name, index=False)
    merged_files.append(new_file_name)

print("Merged files created:")
for file in merged_files:
  print(file)

Merged files created:
game_game_info_merged.csv
game_game_summary_merged.csv
game_team_info_common_merged.csv
game_info_game_summary_merged.csv
draft_history_game_summary_merged.csv
draft_combine_stats_game_summary_merged.csv
team_team_details_merged.csv
team_team_history_merged.csv
team_details_team_history_merged.csv
team_details_team_info_common_merged.csv
draft_history_team_details_merged.csv
team_history_team_info_common_merged.csv
draft_history_team_history_merged.csv
draft_history_team_info_common_merged.csv
draft_combine_stats_draft_history_merged.csv